# Site settings
title: 阿拉伯的鞋匠
email: leonhe86@gmail.com
description: 生活、技术、读书、思考
url: "http://feiio.com"
permalink: :year/:month/:day/:title/
# Build settings
markdown: kramdown
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
site.categories: ['php']

gems: [jekyll-paginate,jekyll-gist]
paginate: 20
paginate_path: "/page/:num"